version: '3'

services:
  api:
    build: .
    restart: always
    hostname: api
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres
    ports:
      - '9000:9000'
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    hostname: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

volumes:
  pgdata:
